name: Build and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to build (client, server, both)'
        required: true
        default: 'both'
        type: choice
        options:
          - client
          - server
          - both
      custom_tags:
        description: 'Custom Docker tags (comma-separated for multiple tags)'
        required: false
        default: ''
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.component }}" == "both" ]; then
            echo "::set-output name=matrix::[{'name':'Client','dockerfile':'client/Dockerfile.prod','image':'guptaashwanee/test-client','context':'client'},{'name':'Server','dockerfile':'server/Dockerfile.prod','image':'guptaashwanee/test-server','context':'server'}]"
          elif [ "${{ github.event.inputs.component }}" == "client" ]; then
            echo "::set-output name=matrix::[{'name':'Client','dockerfile':'client/Dockerfile.prod','image':'guptaashwanee/test-client','context':'client'}]"
          else
            echo "::set-output name=matrix::[{'name':'Server','dockerfile':'server/Dockerfile.prod','image':'guptaashwanee/test-server','context':'server'}]"
          fi
        shell: bash

  build-and-deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          labels: |
            org.opencontainers.image.title=ANSCER ANYA ${{ matrix.name }}
            org.opencontainers.image.description=Anscer Robotics (Robot Control Application) - Anya
            org.opencontainers.image.vendor=ANSCER ROBOTICS
            org.opencontainers.image.source=${{ github.repositoryUrl }}
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.custom_tags != '' ? join(map(steps.meta.outputs.tags, lambda tag: tag.split(':')[0] + ':' + github.event.inputs.custom_tags), ',') : steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
